#!/bin/bash

# This script will create a tarball of the current directory

# clean up
dune clean
./rm_semicolons
rm -rf _build
# Remove files generated by TeX compilation
find . -type f \( -name '*.aux' -o -name '*.log' -o -name '*.nlo' -o -name '*.out' -o -name '*synctex.gz' -o -name '*.toc' \) -delete

ARCHIVE_NAME=$(basename "$(pwd)").tar

# Create a tarball of the current directory
tar -cf "$ARCHIVE_NAME" bin/ lib/ test/ configs/ levels/ rapport/ dune dune-project dune-workspace README.md

echo "Archive created: $ARCHIVE_NAME"
